# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GroupSight 
subtitle: Workshop on Human Computation for Image and Video Analysis
email: gen@cs.brown.edu 
description: > # this means to ignore newlines until "baseurl:"
  GroupSight 

# Build settings
markdown: kramdown
baseurl: "/groupsight-workshop"
url: "http://genp.github.io"
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM